### ISSUE TITLE
encoding argument error

### ISSUE THREAD

**Issue by hussamh10** [screendriver/pypygo#1]
TypeError: **init**() got an unexpected keyword argument 'encoding'
![image](https://cloud.githubusercontent.com/assets/11413675/15801129/3b3c60ea-2a94-11e6-9979-6dda181918fa.png)

**Comment by screendriver** [comment]
Hmm I can't reproduce it.

``` sh
(env) ❯ python
Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypygo
>>> p = pypygo.query("Github")
>>> p.abstract
'GitHub is a web-based Git repository hosting service. It offers all of the distributed revision control and source code management functionality of Git as well as adding its own features. Unlike Git, which is strictly a command-line tool, GitHub provides a Web-based graphical interface and desktop as well as mobile integration. It also provides access control and several collaboration features such as bug tracking, feature requests, task management, and wikis for every project.'
>>> 
```

Maybe it's because you are using Windows and there is some encoding issue on your machine? Unfortunately I don't have a Windows machine where I could test it.

**Comment by s2-t2** [comment]
I have the same issue and am running on arch linux. 

`[sujata@archhost app]$ python 
Python 3.6.3 (default, Oct 24 2017, 14:48:20) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypygo
>>> p = pypygo.query("Github")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/pypygo-0.1.1-py3.6.egg/pypygo/main.py", line 14, in query
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.6/site-packages/simplejson/__init__.py", line 534, in loads
    return cls(encoding=encoding, **kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
>>> 
`

**Comment by screendriver** [comment]
Since I can't reproduce it any help / PR would be welcome
